### ISSUE TITLE
[Forge Version Check/WARN]: Failed to process update information

### ISSUE THREAD

**Issue by Yourname942** [EwyBoy/CHA-S#2]
**Error:**
```
[09:44:30] [Forge Version Check/INFO]: [craftablehorsearmour] Starting version check at http://myurl.me/
[09:44:30] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:899) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:214) [?:?]
	at net.minecraftforge.fml.VersionChecker$1$$Lambda$12089/1931026536.accept(Unknown Source) [?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_51]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	... 7 more
```

**latest log:** [Here](https://gist.github.com/Yourname942/470998972620b1eda42740056234595c#file-latest-log-9-47am-8_20_20)
**Highlighted code:** [Here](https://gist.github.com/Yourname942/470998972620b1eda42740056234595c#file-latest-log-9-47am-8_20_20-L1830-L1846)

**Environment**
- Minecraft 1.15.2
- Forge 31.2.36
- Craftable Horse Armour & Saddle [CHA&S]  v3a

**Steps to reproduce**
1. Click play in Twitch App
2. Click play in Minecraft Launcher
3. Create a new world
4. Enter world
5. Exit world

**Comment by EwyBoy** [comment]
Hey, thanks for reporting. I will try get this fixed asap!

**Comment by EwyBoy** [comment]
Fixed
